### ISSUE TITLE
Feature request: `VPNSP` `custom` for custom configurations

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#611]
## Questions

1. Should we remove Wireguard support for `VPNSP=torguard` and `VPNSP="vpn unlimited"` in favor of using `VPNSP=custom` to have cleaner code / less duplication?

## Notes

This adds preliminary support for Wireguard for Cyberghost, WeVPN, NordVPN and Surfshark.

## TODOs

- [x] Support `custom` as a value for `VPNSP`
- [x] Setup `custom` provider
  - [x] Custom Wireguard configuration (from env, then from files, see #610)
  - [x] Custom OpenVPN configuration (but keep older code for retro-compat, maybe only enable with `v4` release)

**Comment by qdm12** [comment]
Done with:

- OpenVPN: f807f756eb6ba92d1653c4e73c487e76d1bb9702
- Wireguard: 8645d978ba84b68a012356a0e5d40a770d487803
